---
# This is a role for setting up the client.

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

# Install hashcat
- name: Install hashcat
  apt:
    pkg:
     - hashcat

...
