---
# This is a role for setting up the client.

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

# Install hashcat
- name: Install hashcat
  apt:
    pkg:
     - hashcat
     
- name: Change root password
  user:
    name: root
    password: '{{ root_password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Add user user to shadow group
  user:
    name: user
    groups: shadow
    append: yes

- name: Change permissions of /etc/shadow file
  file:
    path: /etc/shadow
    mode: "0640"

...
