---
# This is a role for setting up the client.

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

# Install package
- name: Install packages
  apt:
    pkg:
     - hashcat
     - rar
     - unrar
#     - unzip
     - git
     - snapd
    update_cache: yes
    
# Install John-the-ripper
- name: Install john-the-ripper
  shell: sudo snap install john-the-ripper

- name: Add user user to shadow group
  user:
    name: user
    groups: shadow
    append: yes
    
- name: Change root password
  user:
    name: root
    password: '{{ root_password | password_hash(''sha512'') }}'
    shell: '/bin/bash'
  
- name: Change permissions of /etc/shadow file
  file:
    path: /etc/shadow
    mode: "0640"
    
- name: Create file protected.rar
  copy:
    src: protected.rar
    dest: /home/user/protected.rar
    owner: user
    group: user
    mode: "0644"
  
...
