---
# This is a role for setting up the client.

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

# Install package
- name: Install packages
  apt:
    pkg:
#     - hashcat
     - unzip
     - git
     - snapd
    update_cache: yes
    
- name: Clone hashcat
  git: 
    repo: sudo git clone https://github.com/hashcat/hashcat.git -y
    dest: /home/user
    
# Install John-the-ripper
- name: Install john-the-ripper
  shell: sudo snap install john-the-ripper

- name: Add user user to shadow group
  user:
    name: user
    groups: shadow
    append: yes
    
- name: Change root password
  user:
    name: root
    password: '{{ root_password | password_hash(''sha512'') }}'
    shell: '/bin/bash'
  
- name: Change permissions of /etc/shadow file
  file:
    path: /etc/shadow
    mode: "0640"
    
- name: Create file flag.zip
  copy:
    src: flag.zip
    dest: /home/user/flag.zip
    owner: user
    group: user
    mode: "0644"
  
...
