---
# This is a role for setting up the client.

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

# Install hashcat
- name: Install packages
  apt:
    pkg:
     - hashcat
     - unzip
     - git
     - snapd
    update_cache: yes
# Install John-the-ripper
- name: Install john-the-ripper
  shell: sudo snap install john-the-ripper -y

- name: Add user user to shadow group
  user:
    name: user
    groups: shadow
    append: yes

- name: Change permissions of /etc/shadow file
  file:
    path: /etc/shadow
    mode: "0640"
    
- name: Create file flag.zip
  copy:
    src: flag.zip
    dest: /home/user/flag.zip
    owner: user
    group: user
    mode: "0644"
  
...
