---
# This is a role for setting up the client.

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

# Install hashcat
- name: Install packages
  apt:
    pkg:
     - hashcat
     - unzip
     - git
    update_cache: yes
# Install John
- name: Clone John the Ripper repository
  git:
    repo: https://github.com/openwall/john.git
    dest: /home/user/john

- name: Configure John the Ripper
  shell: ./configure --without-openssl && make
  ignore_errors: true
     
- name: Change root password
  user:
    name: root
    password: '{{ root_password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Add user user to shadow group
  user:
    name: user
    groups: shadow
    append: yes

- name: Change permissions of /etc/shadow file
  file:
    path: /etc/shadow
    mode: "0640"
    
- name: Create file protected.zip
  copy:
    src: protected.zip
    dest: /home/user/protected.zip
    owner: user
    group: user
    mode: "0644"
  
...
