---

- name: disable qxl
  hosts:
      - routers
      - hosts
  gather_facts: yes
  become: yes
  tasks:
      - include_role:
            name: kypo-disable-qxl
        when: ansible_os_family == 'Debian'

- name: set up client
  hosts: client
  become: yes
  become_method: su
  vars:
    root_password: "strongpass"
  roles:
    - name: kypo-user-access
      kypo_user_access_username: user
      kypo_user_access_password: Password123
      kypo_user_access_sudo: True
  task:
    - name: Task with conditional privilege escalation
      when: kypo_user_access_sudo | default(False)
      become: yes
      become_ask_pass: True
    - name: client
      
- name: set up command logging
  hosts: hosts
  become: yes
  roles:
    - role: sandbox-logging
      slf_destination_port: '{% if hostvars["man"] is defined -%} 514 {%- else -%} 515 {%- endif %}'

- name: Run post-build command
  hosts: client
  become: true


...
